// Pure reducer for a Caption Wars room. RoomDO (src/worker/room-do.ts) is a
// thin persistence + HTTP shell around this file: every rule that decides what
// the room DOES lives here, so it can be tested without a Durable Object.
//
// Every function is a pure transform: (state, ...) -> result. No I/O, no
// Date.now() inside (the caller passes `now`, which in production is the DO's
// own clock). Ids (room code, player id, caption id) are generated by the
// caller (src/shared/ids.ts) and passed in, for the same reason.
//
// Results never throw on user errors: every mutating function returns
// `{ state, error? }`. `state` is unchanged when `error` is set.
//
// Design note on "connected" (HOW decision, not in the plan's literal text):
// the plan's Player type has no "eligible this round" field, so this reducer
// reuses `connected` for that purpose: true = this player is part of the
// current round and is required for the phase to auto-advance; false = this
// player joined mid-round and is a spectator until the NEXT round starts.
// `start()` and the reveal->caption branch of `advance()` reset every
// player's `connected` to true, which is what activates a mid-round joiner.
// There is no separate network-presence/heartbeat feature in this MVP, so
// there is no other use of `connected` to conflict with.
//
// Design note on `advance()` (HOW decision the plan explicitly left open):
// going from `reveal` to the next round's `caption` phase needs a freshly
// fetched photo, which is I/O and cannot happen inside a pure function.
// `advance()` takes the next photo as an optional argument. When the caller
// (the DO) does not have one yet, `advance()` makes no change and returns
// `{ state, needsPhoto: true }` so the DO knows to fetch a photo and call
// `advance()` again with it. Advancing to `done` (last round already played)
// needs no photo and always completes in one call.

import type { Caption, Phase, Photo, Player, RoomOptions, RoomState, RoundResult } from './types';
import { normalizeOptions, nextPollMsFor, CAPTION_MAX_CHARS, MAX_HUMAN_PLAYERS } from './config';

export interface RoomResult {
  state: RoomState;
  error?: string;
}

export interface AdvanceResult extends RoomResult {
  needsPhoto?: boolean;
}

function bump(state: RoomState, patch: Partial<RoomState>, phase: Phase): RoomState {
  return {
    ...state,
    ...patch,
    phase,
    version: state.version + 1,
    nextPollMs: nextPollMsFor(phase),
  };
}

function isEligible(p: Player): boolean {
  return p.connected;
}

function eligiblePlayers(state: RoomState): Player[] {
  return state.players.filter(isEligible);
}

export function allEligibleCaptioned(state: RoomState): boolean {
  const eligible = eligiblePlayers(state);
  if (eligible.length === 0) return false;
  return eligible.every((p) => state.captions.some((c) => c.playerId === p.id));
}

export function allEligibleVoted(state: RoomState): boolean {
  const eligible = eligiblePlayers(state);
  if (eligible.length === 0) return false;
  return eligible.every((p) => p.id in state.votes);
}

/** Creates a brand-new room in the lobby. `bots` are already-built Player rows (isBot: true). */
export function createRoom(
  code: string,
  host: { id: string; name: string },
  options: Partial<RoomOptions> | undefined,
  bots: Player[],
  now: number
): RoomState {
  const hostPlayer: Player = {
    id: host.id,
    name: host.name.trim(),
    isBot: false,
    score: 0,
    connected: true,
  };
  return {
    code,
    version: 1,
    phase: 'lobby',
    round: 0,
    options: normalizeOptions(options),
    hostId: host.id,
    players: [hostPlayer, ...bots],
    photo: undefined,
    captions: [],
    votes: {},
    phaseEndsAt: undefined,
    history: [],
    championIds: undefined,
    nextPollMs: nextPollMsFor('lobby'),
  };
}

/**
 * Adds a human player. Lobby joiners are immediately eligible; a joiner
 * during caption/vote/reveal is added as a spectator (`connected: false`)
 * and becomes eligible starting the next round (see the file header note).
 */
export function join(state: RoomState, player: { id: string; name: string }, now: number): RoomResult {
  if (state.phase === 'done') return { state, error: 'game is over' };

  const name = player.name.trim();
  if (name.length === 0) return { state, error: 'name required' };

  const humanCount = state.players.filter((p) => !p.isBot).length;
  if (humanCount >= MAX_HUMAN_PLAYERS) return { state, error: 'room is full' };

  const newPlayer: Player = {
    id: player.id,
    name,
    isBot: false,
    score: 0,
    connected: state.phase === 'lobby',
  };

  const nextState: RoomState = {
    ...state,
    players: [...state.players, newPlayer],
    version: state.version + 1,
  };
  return { state: nextState };
}

/** Host-only, lobby-only. Fetches the first photo (caller's job) and opens round 1. */
export function start(state: RoomState, playerId: string, photo: Photo, now: number): RoomResult {
  if (state.phase !== 'lobby') return { state, error: 'room already started' };
  if (playerId !== state.hostId) return { state, error: 'only the host can start' };

  const players = state.players.map((p) => ({ ...p, connected: true }));
  const nextState = bump(
    { ...state, players },
    {
      round: 1,
      photo,
      captions: [],
      votes: {},
      phaseEndsAt: now + state.options.captionSeconds * 1000,
    },
    'caption'
  );
  return { state: nextState };
}

/**
 * Records one caption. First write per player wins; text is trimmed and must
 * be 1..CAPTION_MAX_CHARS after trimming. Automatically ends the caption
 * phase (-> vote) once every eligible player has captioned, matching the
 * plan's "ends when every eligible player has a caption OR phaseEndsAt
 * passes" rule.
 */
export function submitCaption(
  state: RoomState,
  playerId: string,
  text: string,
  captionId: string,
  now: number
): RoomResult {
  if (state.phase !== 'caption') return { state, error: 'not in caption phase' };

  const player = state.players.find((p) => p.id === playerId);
  if (!player) return { state, error: 'player not in room' };
  if (state.captions.some((c) => c.playerId === playerId)) {
    return { state, error: 'already captioned this round' };
  }

  const trimmed = text.trim();
  if (trimmed.length < 1 || trimmed.length > CAPTION_MAX_CHARS) {
    return { state, error: `caption must be 1-${CAPTION_MAX_CHARS} characters` };
  }

  const caption: Caption = { id: captionId, playerId, text: trimmed };
  const withCaption: RoomState = {
    ...state,
    captions: [...state.captions, caption],
    version: state.version + 1,
  };

  if (allEligibleCaptioned(withCaption)) {
    return endCaptionPhase(withCaption, now);
  }
  return { state: withCaption };
}

/**
 * Ends the caption phase into vote, if it is actually over (all eligible
 * players captioned, or the timer passed). Otherwise a no-op. Safe to call
 * opportunistically (e.g. from a DO alarm) without checking first.
 */
export function endCaptionPhase(state: RoomState, now: number): RoomResult {
  if (state.phase !== 'caption') return { state };
  const timedOut = state.phaseEndsAt !== undefined && now >= state.phaseEndsAt;
  if (!allEligibleCaptioned(state) && !timedOut) return { state };

  const nextState = bump(
    state,
    { votes: {}, phaseEndsAt: now + state.options.voteSeconds * 1000 },
    'vote'
  );
  return { state: nextState };
}

/** Tally of votes per caption id, plus which caption id(s) are the winner(s) (all ties win). */
export function tally(
  captions: Caption[],
  votes: Record<string, string>
): { counts: Record<string, number>; winnerCaptionIds: string[] } {
  const counts: Record<string, number> = {};
  for (const c of captions) counts[c.id] = 0;
  for (const captionId of Object.values(votes)) {
    if (captionId in counts) counts[captionId] += 1;
  }
  const values = Object.values(counts);
  const max = values.length > 0 ? Math.max(...values) : 0;
  const winnerCaptionIds = max > 0 ? Object.entries(counts).filter(([, n]) => n === max).map(([id]) => id) : [];
  return { counts, winnerCaptionIds };
}

/**
 * Records one vote. First write per player wins; cannot vote for your own
 * caption. Automatically ends the vote phase (-> reveal) once every eligible
 * player has voted, matching the plan's "every tied top caption wins" and
 * void-round rules.
 */
export function submitVote(state: RoomState, playerId: string, captionId: string, now: number): RoomResult {
  if (state.phase !== 'vote') return { state, error: 'not in vote phase' };

  const player = state.players.find((p) => p.id === playerId);
  if (!player) return { state, error: 'player not in room' };
  if (playerId in state.votes) return { state, error: 'already voted this round' };

  const caption = state.captions.find((c) => c.id === captionId);
  if (!caption) return { state, error: 'unknown caption' };
  if (caption.playerId === playerId) return { state, error: 'cannot vote for your own caption' };

  const withVote: RoomState = {
    ...state,
    votes: { ...state.votes, [playerId]: captionId },
    version: state.version + 1,
  };

  if (allEligibleVoted(withVote)) {
    return endVotePhase(withVote, now);
  }
  return { state: withVote };
}

/**
 * Ends the vote phase into reveal, if it is actually over. Tallies votes,
 * awards points equal to votes received to every tied top caption's author,
 * and voids the round (no winner, no points) when fewer than 2 captions
 * exist. A void round is represented as `winnerCaptionIds: []` on the
 * RoundResult; there is no separate flag in the plan's RoundResult shape.
 */
export function endVotePhase(state: RoomState, now: number): RoomResult {
  if (state.phase !== 'vote') return { state };
  const timedOut = state.phaseEndsAt !== undefined && now >= state.phaseEndsAt;
  if (!allEligibleVoted(state) && !timedOut) return { state };

  const void_ = state.captions.length < 2;
  const { counts, winnerCaptionIds: tallied } = tally(state.captions, state.votes);
  const winnerCaptionIds = void_ ? [] : tallied;

  const players = state.players.map((p) => {
    const won = winnerCaptionIds
      .map((id) => state.captions.find((c) => c.id === id))
      .filter((c): c is Caption => c !== undefined && c.playerId === p.id);
    if (won.length === 0) return p;
    const gained = won.reduce((sum, c) => sum + (counts[c.id] ?? 0), 0);
    return { ...p, score: p.score + gained };
  });

  const result: RoundResult = {
    round: state.round,
    photo: state.photo as Photo,
    captions: state.captions,
    votes: state.votes,
    winnerCaptionIds,
  };

  const nextState = bump(
    { ...state, players },
    {
      history: [...state.history, result],
      phaseEndsAt: now + state.options.revealSeconds * 1000,
    },
    'reveal'
  );
  return { state: nextState };
}

function computeChampionIds(players: Player[]): string[] {
  if (players.length === 0) return [];
  const maxScore = Math.max(...players.map((p) => p.score));
  return players.filter((p) => p.score === maxScore).map((p) => p.id);
}

/**
 * Advances out of reveal: either into the next round's caption phase (needs
 * a photo, see the file header note) or into `done` after the last round.
 * `actorId` is a player id (must be the host) or the literal string 'timer'
 * for the reveal-timeout auto-advance. No-op (not an error) when called
 * outside `reveal`, so a redundant timer/host call is harmless.
 */
export function advance(state: RoomState, actorId: string | 'timer', now: number, photo?: Photo): AdvanceResult {
  if (state.phase !== 'reveal') return { state };
  if (actorId !== 'timer' && actorId !== state.hostId) {
    return { state, error: 'only the host can advance' };
  }

  if (state.round >= state.options.rounds) {
    const nextState = bump(state, { championIds: computeChampionIds(state.players) }, 'done');
    return { state: nextState };
  }

  if (!photo) return { state, needsPhoto: true };

  const players = state.players.map((p) => ({ ...p, connected: true }));
  const nextState = bump(
    { ...state, players },
    {
      round: state.round + 1,
      photo,
      captions: [],
      votes: {},
      phaseEndsAt: now + state.options.captionSeconds * 1000,
    },
    'caption'
  );
  return { state: nextState };
}

export type PublicCaption = { id: string; text: string; playerId?: string };
export interface PublicRoomState extends Omit<RoomState, 'captions'> {
  captions: PublicCaption[];
}

/**
 * The view of state sent to one specific player: captions are anonymized
 * during `vote` (no playerId), and during `caption` a player only sees their
 * own submission (not other players' in-progress captions). Every other
 * phase, and every other field, is shown as-is.
 */
export function publicView(state: RoomState, viewerId: string): PublicRoomState {
  let captions: PublicCaption[];
  if (state.phase === 'caption') {
    captions = state.captions
      .filter((c) => c.playerId === viewerId)
      .map((c) => ({ id: c.id, text: c.text, playerId: c.playerId }));
  } else if (state.phase === 'vote') {
    captions = state.captions.map((c) => ({ id: c.id, text: c.text }));
  } else {
    captions = state.captions.map((c) => ({ id: c.id, text: c.text, playerId: c.playerId }));
  }
  return { ...state, captions };
}
