// Pure reducer for a Caption Wars room. RoomDO (src/worker/room-do.ts) is a
// thin persistence + HTTP shell around this file: every rule that decides what
// the room DOES lives here, so it can be tested without a Durable Object.
//
// Every function is a pure transform: (state, ...) -> result. No I/O, no
// Date.now() inside (the caller passes `now`, which in production is the DO's
// own clock). Ids (room code, player id, caption id, job id) are generated by
// the caller (src/shared/ids.ts) and passed in, for the same reason.
//
// Results never throw on user errors: every mutating function returns
// `{ state, error? }`. `state` is unchanged when `error` is set.
//
// --- Two design notes the plan's amendments settle -------------------------
//
// 1. Who may act this round: `roundPlayerIds`, frozen when the round opens
//    (amendment 7). Only those ids may caption or vote, and "everyone acted"
//    means everyone in that list. Someone who joins mid-round watches as a
//    spectator and is added to the roster when the NEXT round opens.
//    `Player.lastSeenAt` is display only and never affects eligibility.
//
// 2. `advance()` and the next round's photo: fetching a photo is I/O and
//    cannot happen inside a pure function. `advance()` takes the next photo as
//    an optional argument. Without one it makes no change and returns
//    `{ state, needsPhoto: true }`, so the DO knows to fetch and call again.
//    Advancing to `done` after the last round needs no photo.

import type {
  BotJob,
  Caption,
  Phase,
  PhotoMeta,
  Player,
  PublicCaption,
  PublicRoomState,
  RoomOptions,
  RoomResult,
  RoomState,
  RoundResult,
  VoteCaption,
} from './types';
import {
  CAPTION_MAX_CHARS,
  MAX_HUMAN_PLAYERS,
  PHOTO_MAX_ATTEMPTS,
  REVEAL_MIN_MS,
  ROOM_TTL_MS,
  nextPollMsFor,
  normalizeOptions,
  photoRetryDelayMs,
} from './config';
import { hashSeed, seededShuffle } from './rng';
import { sanitizeCaption, sanitizeName } from './text';

export type { RoomResult };

export interface AdvanceResult extends RoomResult {
  /** The caller must fetch a photo and call again with it before the next round can open. */
  needsPhoto?: boolean;
}

/** The three fields a slow, awaiting caller re-checks before it is allowed to mutate. */
export interface StateStamp {
  phase: Phase;
  round: number;
  version: number;
}

export function stampOf(state: RoomState): StateStamp {
  return { phase: state.phase, round: state.round, version: state.version };
}

/**
 * Exact match, version included: "nothing at all happened while I was away".
 * Use this when the awaiting caller is the only one who should have been able
 * to act (fetching the photo that opens a round).
 */
export function stampMatches(state: RoomState, stamp: StateStamp): boolean {
  return (
    state.phase === stamp.phase && state.round === stamp.round && state.version === stamp.version
  );
}

/**
 * The looser check the bots use: "the room is still in the same round and
 * phase". Version is deliberately NOT compared here, because two bots run
 * concurrently and the first one's caption bumps the version: comparing
 * versions would silently throw away the second bot every single round.
 */
export function roundMatches(state: RoomState, stamp: StateStamp): boolean {
  return state.phase === stamp.phase && state.round === stamp.round;
}

/** Applies a patch, moves to `phase`, bumps the version, and restamps the phase clock. */
function bump(state: RoomState, patch: Partial<RoomState>, phase: Phase, now: number): RoomState {
  return {
    ...state,
    ...patch,
    phase,
    phaseStartedAt: now,
    version: state.version + 1,
    nextPollMs: nextPollMsFor(phase),
  };
}

// --- eligibility -------------------------------------------------------------

export function isInRound(state: RoomState, playerId: string): boolean {
  return state.roundPlayerIds.includes(playerId);
}

/**
 * True when this player has at least one caption they are allowed to vote for.
 * A player with no votable option (only their own caption exists) counts as
 * having acted, so a one-caption round does not stall until the timer.
 */
function hasVotableCaption(state: RoomState, playerId: string): boolean {
  return state.captions.some((c) => c.playerId !== playerId);
}

/**
 * True when this id is a BOT whose job for the current round and phase has
 * already ended in `failed`: the model was down, timed out, answered nothing
 * usable, or was reaped past its deadline. That bot is never going to act, so
 * counting it as "still to come" makes the humans watch the full timer run down
 * on a round nobody is playing (up to 55 seconds of dead air with 2 dead bots).
 * A failed job is terminal: buildBotJobs makes exactly one job per bot per
 * phase, so there is no second attempt waiting behind it.
 */
function botGaveUp(state: RoomState, playerId: string, phase: 'caption' | 'vote'): boolean {
  const player = state.players.find((p) => p.id === playerId);
  if (!player || !player.isBot) return false;
  return state.botJobs.some(
    (j) =>
      j.botId === playerId &&
      j.round === state.round &&
      j.phase === phase &&
      j.status === 'failed'
  );
}

export function allEligibleCaptioned(state: RoomState): boolean {
  if (state.roundPlayerIds.length === 0) return false;
  return state.roundPlayerIds.every(
    (id) => state.captions.some((c) => c.playerId === id) || botGaveUp(state, id, 'caption')
  );
}

export function allEligibleVoted(state: RoomState): boolean {
  if (state.roundPlayerIds.length === 0) return false;
  return state.roundPlayerIds.every(
    (id) => id in state.votes || !hasVotableCaption(state, id) || botGaveUp(state, id, 'vote')
  );
}

// --- lifecycle ---------------------------------------------------------------

/** Creates a brand-new room in the lobby. `bots` are already-built Player rows (isBot: true). */
export function createRoom(
  code: string,
  host: { id: string; name: string },
  options: Partial<RoomOptions> | undefined,
  bots: Player[],
  now: number
): RoomState {
  const hostPlayer: Player = {
    id: host.id,
    name: sanitizeName(host.name),
    isBot: false,
    score: 0,
    lastSeenAt: now,
  };
  return {
    code,
    version: 1,
    phase: 'lobby',
    round: 0,
    options: normalizeOptions(options),
    hostId: host.id,
    players: [hostPlayer, ...bots],
    roundPlayerIds: [],
    photo: undefined,
    captions: [],
    votes: {},
    createdAt: now,
    expiresAt: now + ROOM_TTL_MS,
    phaseStartedAt: now,
    phaseEndsAt: undefined,
    botJobs: [],
    history: [],
    championIds: undefined,
    nextPollMs: nextPollMsFor('lobby'),
  };
}

/**
 * Adds a human player. A lobby joiner is in the next round automatically
 * (the roster is frozen at `start`); a joiner during caption/vote/reveal
 * watches this round and joins the roster when the next round opens.
 */
export function join(
  state: RoomState,
  player: { id: string; name: string },
  now: number
): RoomResult {
  if (state.phase === 'done') return { state, error: 'this game is over' };

  const name = sanitizeName(player.name);
  if (name.length === 0) return { state, error: 'name required' };

  const humanCount = state.players.filter((p) => !p.isBot).length;
  if (humanCount >= MAX_HUMAN_PLAYERS) return { state, error: 'this room is full' };

  const newPlayer: Player = { id: player.id, name, isBot: false, score: 0, lastSeenAt: now };

  return {
    state: {
      ...state,
      players: [...state.players, newPlayer],
      version: state.version + 1,
    },
  };
}

/**
 * Records that a player is still around. Display only, so it deliberately does
 * NOT bump `version`: a poll must not look like a state change, or every client
 * would re-render on every other client's heartbeat.
 */
export function touch(state: RoomState, playerId: string, now: number): RoomState {
  const idx = state.players.findIndex((p) => p.id === playerId);
  if (idx === -1 || state.players[idx].lastSeenAt === now) return state;
  const players = state.players.slice();
  players[idx] = { ...players[idx], lastSeenAt: now };
  return { ...state, players };
}

/** Opens round 1. Host only, lobby only. The caller supplies the already-fetched photo. */
export function start(
  state: RoomState,
  playerId: string,
  photo: PhotoMeta,
  now: number
): RoomResult {
  if (state.phase !== 'lobby') return { state, error: 'this game already started' };
  if (playerId !== state.hostId) return { state, error: 'only the host can start' };

  return { state: openRound(state, 1, photo, now) };
}

/**
 * Freezes the roster and opens a caption phase for `round`.
 *
 * The room's expiry is pushed out here as well: a 20-round game at the maximum
 * timers is exactly the 2h TTL, so a long game would otherwise be deleted from
 * under the players mid-round.
 */
function openRound(state: RoomState, round: number, photo: PhotoMeta, now: number): RoomState {
  return bump(
    state,
    {
      round,
      roundPlayerIds: state.players.map((p) => p.id),
      photo,
      captions: [],
      votes: {},
      botJobs: [],
      phaseEndsAt: now + state.options.captionSeconds * 1000,
      expiresAt: Math.max(state.expiresAt, now + ROOM_TTL_MS),
      photoRetry: undefined,
    },
    'caption',
    now
  );
}

// --- player actions ----------------------------------------------------------

/**
 * Records one caption. First write per player wins; the text is sanitized
 * (one line, trimmed, capped) and must be 1..CAPTION_MAX_CHARS afterwards.
 * Ends the caption phase automatically once everyone in the round roster has
 * captioned.
 */
export function submitCaption(
  state: RoomState,
  playerId: string,
  text: string,
  captionId: string,
  now: number
): RoomResult {
  if (state.phase !== 'caption') return { state, error: 'not in the caption phase' };
  if (!state.players.some((p) => p.id === playerId)) return { state, error: 'player not in room' };
  if (!isInRound(state, playerId)) return { state, error: 'you are in from the next round' };
  if (state.captions.some((c) => c.playerId === playerId)) {
    return { state, error: 'you already captioned this round' };
  }

  const clean = sanitizeCaption(text);
  if (clean.length < 1) return { state, error: 'caption cannot be empty' };
  if (clean.length > CAPTION_MAX_CHARS) {
    return { state, error: `caption must be at most ${CAPTION_MAX_CHARS} characters` };
  }

  const caption: Caption = { id: captionId, playerId, text: clean };
  const withCaption: RoomState = {
    ...state,
    captions: [...state.captions, caption],
    version: state.version + 1,
  };

  if (allEligibleCaptioned(withCaption)) return endCaptionPhase(withCaption, now);
  return { state: withCaption };
}

/**
 * Ends the caption phase into vote, if it is actually over (everyone in the
 * roster captioned, or the timer passed). Otherwise a no-op, so it is safe to
 * call opportunistically from the alarm or from any request.
 */
export function endCaptionPhase(state: RoomState, now: number): RoomResult {
  if (state.phase !== 'caption') return { state };
  const timedOut = state.phaseEndsAt !== undefined && now >= state.phaseEndsAt;
  if (!allEligibleCaptioned(state) && !timedOut) return { state };

  const voting = bump(
    state,
    { votes: {}, phaseEndsAt: now + state.options.voteSeconds * 1000 },
    'vote',
    now
  );

  // A vote phase can be over the moment it opens: a round with fewer than two
  // captions is void whatever anyone does, so nobody should sit and watch a
  // 30-second timer run down on a ballot that cannot produce a winner.
  return endVotePhase(voting, now);
}

/**
 * Records one vote. First write per player wins; you cannot vote for your own
 * caption (also enforced in the view: your caption comes back canVote: false).
 * Ends the vote phase automatically once everyone who can vote has.
 */
export function submitVote(
  state: RoomState,
  playerId: string,
  captionId: string,
  now: number
): RoomResult {
  if (state.phase !== 'vote') return { state, error: 'not in the vote phase' };
  if (!state.players.some((p) => p.id === playerId)) return { state, error: 'player not in room' };
  if (!isInRound(state, playerId)) return { state, error: 'you are in from the next round' };
  if (playerId in state.votes) return { state, error: 'you already voted this round' };

  const caption = state.captions.find((c) => c.id === captionId);
  if (!caption) return { state, error: 'that caption is not in this round' };
  if (caption.playerId === playerId) return { state, error: 'you cannot vote for your own caption' };

  const withVote: RoomState = {
    ...state,
    votes: { ...state.votes, [playerId]: captionId },
    version: state.version + 1,
  };

  if (allEligibleVoted(withVote)) return endVotePhase(withVote, now);
  return { state: withVote };
}

/** Votes per caption id, plus which caption id(s) won. Every tied top caption wins. */
export function tally(
  captions: Caption[],
  votes: Record<string, string>
): { counts: Record<string, number>; winnerCaptionIds: string[] } {
  const counts: Record<string, number> = {};
  for (const c of captions) counts[c.id] = 0;
  for (const captionId of Object.values(votes)) {
    if (captionId in counts) counts[captionId] += 1;
  }
  const values = Object.values(counts);
  const max = values.length > 0 ? Math.max(...values) : 0;
  const winnerCaptionIds =
    max > 0
      ? Object.entries(counts)
          .filter(([, n]) => n === max)
          .map(([id]) => id)
      : [];
  return { counts, winnerCaptionIds };
}

/**
 * Why a void round scored nothing, in the terms a player can act on.
 *
 * A solo game with two AI players and a model that is down produces a round
 * where the only human wrote a caption and nothing else arrived. "Not enough
 * captions" reads as an accusation; "the AI players had nothing to say" is what
 * actually happened. Any `failed` bot job this round is the tell.
 */
function voidReasonFor(state: RoomState): 'no-captions' | 'bots-failed' {
  const botsFailed = state.botJobs.some(
    (j) => j.round === state.round && j.phase === 'caption' && j.status === 'failed'
  );
  return botsFailed ? 'bots-failed' : 'no-captions';
}

/**
 * Ends the vote phase into reveal, if it is actually over. Points = votes
 * received, awarded to every tied top caption's author. A round with fewer
 * than 2 captions is void: no winner, no points, represented as
 * `winnerCaptionIds: []` plus a `voidReason` on the RoundResult.
 */
export function endVotePhase(state: RoomState, now: number): RoomResult {
  if (state.phase !== 'vote') return { state };
  // Fewer than 2 captions is void no matter who votes, so the round is over the
  // moment it is in that shape: do not run a timer on an unwinnable ballot.
  const isVoid = state.captions.length < 2;
  const timedOut = state.phaseEndsAt !== undefined && now >= state.phaseEndsAt;
  if (!isVoid && !allEligibleVoted(state) && !timedOut) return { state };

  const { counts, winnerCaptionIds: tallied } = tally(state.captions, state.votes);
  const winnerCaptionIds = isVoid ? [] : tallied;

  const players = state.players.map((p) => {
    const won = winnerCaptionIds
      .map((id) => state.captions.find((c) => c.id === id))
      .filter((c): c is Caption => c !== undefined && c.playerId === p.id);
    if (won.length === 0) return p;
    const gained = won.reduce((sum, c) => sum + (counts[c.id] ?? 0), 0);
    return { ...p, score: p.score + gained };
  });

  const result: RoundResult = {
    round: state.round,
    photo: state.photo as PhotoMeta,
    captions: state.captions,
    votes: state.votes,
    winnerCaptionIds,
    ...(isVoid ? { voidReason: voidReasonFor(state) } : {}),
  };

  return {
    state: bump(
      { ...state, players },
      {
        history: [...state.history, result],
        phaseEndsAt: now + state.options.revealSeconds * 1000,
      },
      'reveal',
      now
    ),
  };
}

function computeChampionIds(players: Player[]): string[] {
  if (players.length === 0) return [];
  const maxScore = Math.max(...players.map((p) => p.score));
  return players.filter((p) => p.score === maxScore).map((p) => p.id);
}

/**
 * Advances out of reveal: into the next round's caption phase (needs a photo,
 * see the header note) or into `done` after the last round.
 *
 * `actorId` is a player id (must be the host) or the literal 'timer' for the
 * reveal-timeout auto-advance. The host may only skip reveal once it has been
 * on screen for `revealMinMs` (the reveal floor); the timer only fires once
 * `phaseEndsAt` has passed. Calling it outside `reveal` is a silent no-op, so a
 * redundant host tap or a late alarm is harmless.
 */
export function advance(
  state: RoomState,
  actorId: string | 'timer',
  now: number,
  photo?: PhotoMeta,
  revealMinMs: number = REVEAL_MIN_MS
): AdvanceResult {
  if (state.phase !== 'reveal') return { state };

  if (actorId === 'timer') {
    if (state.phaseEndsAt !== undefined && now < state.phaseEndsAt) return { state };
  } else {
    if (actorId !== state.hostId) return { state, error: 'only the host can move on' };
    if (now < state.phaseStartedAt + revealMinMs) {
      return { state, error: 'give everyone a second to see the scores' };
    }
  }

  if (state.round >= state.options.rounds) {
    return {
      state: bump(
        state,
        { championIds: computeChampionIds(state.players), photoRetry: undefined },
        'done',
        now
      ),
    };
  }

  if (!photo) return { state, needsPhoto: true };
  return { state: openRound(state, state.round + 1, photo, now) };
}

/**
 * Runs every clock-driven transition that is due, in a loop, so a room that
 * nobody has polled for a while catches up in one pass. Stops as soon as it
 * needs a photo (the caller fetches one and calls again) or nothing more is
 * due. This is the pure core of the DO's `advanceIfDue`; the DO adds the photo
 * fetch and the storage write.
 */
export function advanceIfDue(
  state: RoomState,
  now: number,
  revealMinMs: number = REVEAL_MIN_MS
): AdvanceResult {
  let current = state;
  // At most one full round of transitions (caption -> vote -> reveal -> next)
  // can complete per call before a photo is needed, so 4 passes is the ceiling.
  for (let i = 0; i < 4; i++) {
    const before = current;

    if (current.phase === 'caption') current = endCaptionPhase(current, now).state;
    else if (current.phase === 'vote') current = endVotePhase(current, now).state;
    else if (current.phase === 'reveal') {
      const res = advance(current, 'timer', now, undefined, revealMinMs);
      if (res.needsPhoto) return { state: current, needsPhoto: true };
      current = res.state;
    }

    if (current === before) break;
  }
  return { state: current };
}

/**
 * Records that the next round's photo could not be fetched.
 *
 * Without this the room sits in `reveal` with `phaseEndsAt` already in the past,
 * the alarm re-arms to "now", and the Durable Object spins on outbound image
 * fetches until the room expires. So each failure gets a backoff, and after
 * PHOTO_MAX_ATTEMPTS the game ends honestly with `endedReason:
 * 'photo-unavailable'` and the scoreboard everyone already earned.
 *
 * Bookkeeping only, so it deliberately does not bump `version` unless the game
 * actually ends (which players must see).
 */
export function notePhotoFailure(
  state: RoomState,
  now: number,
  maxAttempts: number = PHOTO_MAX_ATTEMPTS
): RoomResult {
  const attempts = (state.photoRetry?.attempts ?? 0) + 1;

  if (attempts >= maxAttempts) {
    return {
      state: bump(
        state,
        {
          championIds: computeChampionIds(state.players),
          endedReason: 'photo-unavailable',
          photoRetry: undefined,
        },
        'done',
        now
      ),
    };
  }

  return {
    state: {
      ...state,
      photoRetry: { attempts, nextAttemptAt: now + photoRetryDelayMs(attempts) },
    },
  };
}

/** True while a failed photo fetch is still serving out its backoff. */
export function photoRetryBlocked(state: RoomState, now: number): boolean {
  return state.photoRetry !== undefined && now < state.photoRetry.nextAttemptAt;
}

// --- bot jobs ----------------------------------------------------------------
//
// Job bookkeeping deliberately does NOT bump `version`: jobs are internal, are
// stripped from every client view, and a status change must not invalidate the
// stamp a running job re-checks before it mutates the room.

export function enqueueBotJobs(state: RoomState, jobs: BotJob[]): RoomState {
  if (jobs.length === 0) return state;
  return { ...state, botJobs: [...state.botJobs, ...jobs] };
}

export function setJobStatus(
  state: RoomState,
  jobId: string,
  status: BotJob['status']
): RoomState {
  const idx = state.botJobs.findIndex((j) => j.jobId === jobId);
  if (idx === -1) return state;
  const botJobs = state.botJobs.slice();
  botJobs[idx] = { ...botJobs[idx], status };
  return { ...state, botJobs };
}

/** Takes the lease on a batch of jobs: status `running` plus the `startedAt` stamp. */
export function markJobsRunning(state: RoomState, jobIds: string[], now: number): RoomState {
  const wanted = new Set(jobIds);
  if (wanted.size === 0) return state;
  let changed = false;
  const botJobs = state.botJobs.map((job) => {
    if (!wanted.has(job.jobId)) return job;
    changed = true;
    return { ...job, status: 'running' as const, startedAt: now };
  });
  return changed ? { ...state, botJobs } : state;
}

/**
 * Marks every `pending` or `running` job past its `deadline` as `failed`.
 *
 * A `running` job whose Durable Object died mid-model-call would otherwise stay
 * `running` forever: never retried (only `pending` jobs are due) and never
 * recorded as finished. Called from the alarm and from settle, so the state
 * machine always converges on a terminal status.
 */
export function reapBotJobs(state: RoomState, now: number): RoomState {
  let changed = false;
  const botJobs = state.botJobs.map((job) => {
    const open = job.status === 'pending' || job.status === 'running';
    if (!open || now < job.deadline) return job;
    changed = true;
    return { ...job, status: 'failed' as const };
  });
  return changed ? { ...state, botJobs } : state;
}

/** A job is still worth running only while its own round and phase are the live ones. */
function isLive(state: RoomState, job: BotJob, now: number): boolean {
  return (
    job.status === 'pending' &&
    now < job.deadline &&
    job.round === state.round &&
    job.phase === state.phase
  );
}

/**
 * Jobs that should run now: live, due, and not a second attempt at work another
 * job already holds or finished. One (botId, round, phase) runs at most once
 * unless the earlier attempt is recorded `failed`.
 */
export function dueBotJobs(state: RoomState, now: number): BotJob[] {
  const claimed = new Set(
    state.botJobs
      .filter((j) => j.status === 'running' || j.status === 'done')
      .map((j) => `${j.botId}:${j.round}:${j.phase}`)
  );
  return state.botJobs.filter(
    (j) =>
      isLive(state, j, now) &&
      j.dueAt <= now &&
      !claimed.has(`${j.botId}:${j.round}:${j.phase}`)
  );
}

/** The earliest moment a pending bot job wants the alarm to fire, if any. */
export function nextBotJobDueAt(state: RoomState, now: number): number | undefined {
  const times = state.botJobs.filter((j) => isLive(state, j, now)).map((j) => j.dueAt);
  return times.length > 0 ? Math.min(...times) : undefined;
}

// --- the client's view -------------------------------------------------------

/** The stable per-round display order, identical on every screen (seeded by code + round). */
export function orderedCaptions(state: RoomState): Caption[] {
  return seededShuffle(state.captions, hashSeed(`${state.code}:${state.round}`));
}

/**
 * The room as one specific player may see it (plan amendments 5 and 9):
 *   - bot jobs are stripped entirely
 *   - during `caption` a player sees only their own caption, so nobody can
 *     copy or pre-judge anyone else's
 *   - during `vote` every caption is a VoteCaption: id, text, isOwn, canVote,
 *     and NEVER an author
 *   - during `caption` and `vote` the live ballot is empty. `votes` is keyed by
 *     PLAYER ID, so shipping it before the reveal shows every screen who voted
 *     for which caption. Only the viewer's own vote comes back, as `yourVote`.
 *   - from `reveal` on, authors and the full ballot are attached
 *   - `serverTime` rides along so the client can measure its clock offset
 */
export function publicView(
  state: RoomState,
  viewerId: string,
  now: number,
  revealMinMs: number = REVEAL_MIN_MS
): PublicRoomState {
  const { botJobs: _botJobs, captions: _captions, votes: _votes, ...rest } = state;
  void _botJobs;
  void _captions;
  void _votes;

  const ballotIsSecret = state.phase === 'caption' || state.phase === 'vote';

  let captions: PublicCaption[];
  if (state.phase === 'lobby') {
    captions = [];
  } else if (state.phase === 'caption') {
    captions = state.captions
      .filter((c) => c.playerId === viewerId)
      .map((c) => ({ id: c.id, text: c.text, playerId: c.playerId }));
  } else if (state.phase === 'vote') {
    const voteCaptions: VoteCaption[] = orderedCaptions(state).map((c) => ({
      id: c.id,
      text: c.text,
      isOwn: c.playerId === viewerId,
      canVote: c.playerId !== viewerId,
    }));
    captions = voteCaptions;
  } else {
    captions = orderedCaptions(state).map((c) => ({
      id: c.id,
      text: c.text,
      playerId: c.playerId,
    }));
  }

  return {
    ...rest,
    captions,
    captionCount: state.captions.length,
    votes: ballotIsSecret ? {} : state.votes,
    yourVote: state.votes[viewerId] ?? null,
    revealMinMs,
    serverTime: now,
  };
}
