// Pure reducer for a Caption Wars room. RoomDO (src/worker/room-do.ts) is a
// thin persistence + HTTP shell around this file: every rule that decides what
// the room DOES lives here, so it can be tested without a Durable Object.
//
// Every function is a pure transform: (state, ...) -> result. No I/O, no
// Date.now() inside (the caller passes `now`, which in production is the DO's
// own clock). Ids (room code, player id, caption id, job id) are generated by
// the caller (src/shared/ids.ts) and passed in, for the same reason.
//
// Results never throw on user errors: every mutating function returns
// `{ state, error? }`. `state` is unchanged when `error` is set.
//
// --- Two design notes the plan's amendments settle -------------------------
//
// 1. Who may act this round: `roundPlayerIds`, frozen when the round opens
//    (amendment 7). Only those ids may caption or vote, and "everyone acted"
//    means everyone in that list. Someone who joins mid-round watches as a
//    spectator and is added to the roster when the NEXT round opens.
//    `Player.lastSeenAt` is display only and never affects eligibility.
//
// 2. `advance()` and the next round's photo: fetching a photo is I/O and
//    cannot happen inside a pure function. `advance()` takes the next photo as
//    an optional argument. Without one it makes no change and returns
//    `{ state, needsPhoto: true }`, so the DO knows to fetch and call again.
//    Advancing to `done` after the last round needs no photo.

import type {
  BotJob,
  Caption,
  Phase,
  PhotoMeta,
  Player,
  PublicCaption,
  PublicRoomState,
  RoomOptions,
  RoomResult,
  RoomState,
  RoundResult,
  VoteCaption,
} from './types';
import {
  MAX_HUMAN_PLAYERS,
  PHOTO_MAX_ATTEMPTS,
  REVEAL_MIN_MS,
  ROOM_TTL_MS,
  nextPollMsFor,
  normalizeOptions,
  photoRetryDelayMs,
} from './config';
import { hashSeed, seededShuffle } from './rng';
import { sanitizeCaption, sanitizeName } from './text';

export type { RoomResult };

export interface AdvanceResult extends RoomResult {
  /** The caller must fetch a photo and call again with it before the next round can open. */
  needsPhoto?: boolean;
}

/** The three fields a slow, awaiting caller re-checks before it is allowed to mutate. */
export interface StateStamp {
  phase: Phase;
  round: number;
  version: number;
}

export function stampOf(state: RoomState): StateStamp {
  return { phase: state.phase, round: state.round, version: state.version };
}

/**
 * Exact match, version included: "nothing at all happened while I was away".
 * Use this when the awaiting caller is the only one who should have been able
 * to act (fetching the photo that opens a round).
 */
export function stampMatches(state: RoomState, stamp: StateStamp): boolean {
  return (
    state.phase === stamp.phase && state.round === stamp.round && state.version === stamp.version
  );
}

/**
 * The looser check the bots use: "the room is still in the same round and
 * phase". Version is deliberately NOT compared here, because two bots run
 * concurrently and the first one's caption bumps the version: comparing
 * versions would silently throw away the second bot every single round.
 */
export function roundMatches(state: RoomState, stamp: StateStamp): boolean {
  return state.phase === stamp.phase && state.round === stamp.round;
}

/** Applies a patch, moves to `phase`, bumps the version, and restamps the phase clock. */
function bump(state: RoomState, patch: Partial<RoomState>, phase: Phase, now: number): RoomState {
  return {
    ...state,
    ...patch,
    phase,
    phaseStartedAt: now,
    version: state.version + 1,
    nextPollMs: nextPollMsFor(phase),
  };
}

// --- eligibility -------------------------------------------------------------

export function isInRound(state: RoomState, playerId: string): boolean {
  return state.roundPlayerIds.includes(playerId);
}

/**
 * True when this player has at least one caption they are allowed to vote for.
 * A player with no votable option (only their own caption exists) counts as
 * having acted, so a one-caption round does not stall until the timer.
 */
function hasVotableCaption(state: RoomState, playerId: string): boolean {
  return state.captions.some((c) => c.playerId !== playerId);
}

/**
 * True when this id is a BOT whose job for the current round and phase has
 * already ended in `failed`: the model was down, timed out, answered nothing
 * usable, or was reaped past its deadline. That bot is never going to act, so
 * counting it as "still to come" makes the humans watch the full timer run down
 * on a round nobody is playing (up to 55 seconds of dead air with 2 dead bots).
 * A failed job is terminal: buildBotJobs makes exactly one job per bot per
 * phase, so there is no second attempt waiting behind it.
 */
function botGaveUp(state: RoomState, playerId: string, phase: 'caption' | 'vote'): boolean {
  const player = state.players.find((p) => p.id === playerId);
  if (!player || !player.isBot) return false;
  // ROUND 7: an offline AI player has given up on EVERY phase, not only the one
  // whose job met the wall. `noteAiOffline` fires during a caption phase, and
  // without this the vote phase that follows would sit the humans in front of a
  // 30-second countdown waiting on two bots that no longer exist. The next round
  // does not have this problem, because they are off the roster by then.
  if (state.aiOffline === true) return true;
  return state.botJobs.some(
    (j) =>
      j.botId === playerId &&
      j.round === state.round &&
      j.phase === phase &&
      j.status === 'failed'
  );
}

export function allEligibleCaptioned(state: RoomState): boolean {
  if (state.roundPlayerIds.length === 0) return false;
  return state.roundPlayerIds.every(
    (id) => state.captions.some((c) => c.playerId === id) || botGaveUp(state, id, 'caption')
  );
}

export function allEligibleVoted(state: RoomState): boolean {
  if (state.roundPlayerIds.length === 0) return false;
  return state.roundPlayerIds.every(
    (id) => id in state.votes || !hasVotableCaption(state, id) || botGaveUp(state, id, 'vote')
  );
}

// --- lifecycle ---------------------------------------------------------------

/** Creates a brand-new room in the lobby. `bots` are already-built Player rows (isBot: true). */
export function createRoom(
  code: string,
  host: { id: string; name: string },
  options: Partial<RoomOptions> | undefined,
  bots: Player[],
  now: number
): RoomState {
  const hostPlayer: Player = {
    id: host.id,
    name: sanitizeName(host.name),
    isBot: false,
    score: 0,
    lastSeenAt: now,
  };
  return {
    code,
    version: 1,
    phase: 'lobby',
    round: 0,
    options: normalizeOptions(options),
    hostId: host.id,
    players: [hostPlayer, ...bots],
    roundPlayerIds: [],
    photo: undefined,
    captions: [],
    votes: {},
    createdAt: now,
    expiresAt: now + ROOM_TTL_MS,
    phaseStartedAt: now,
    phaseEndsAt: undefined,
    botJobs: [],
    history: [],
    championIds: undefined,
    nextPollMs: nextPollMsFor('lobby'),
  };
}

/**
 * Adds a human player. A lobby joiner is in the next round automatically
 * (the roster is frozen at `start`); a joiner during caption/vote/reveal
 * watches this round and joins the roster when the next round opens.
 */
export function join(
  state: RoomState,
  player: { id: string; name: string },
  now: number
): RoomResult {
  if (state.phase === 'done') return { state, error: 'this game is over' };

  const name = sanitizeName(player.name);
  if (name.length === 0) return { state, error: 'name required' };

  const humanCount = state.players.filter((p) => !p.isBot).length;
  if (humanCount >= MAX_HUMAN_PLAYERS) return { state, error: 'this room is full' };

  const newPlayer: Player = { id: player.id, name, isBot: false, score: 0, lastSeenAt: now };

  return {
    state: {
      ...state,
      players: [...state.players, newPlayer],
      version: state.version + 1,
    },
  };
}

/**
 * Records that a player is still around. Display only, so it deliberately does
 * NOT bump `version`: a poll must not look like a state change, or every client
 * would re-render on every other client's heartbeat.
 */
export function touch(state: RoomState, playerId: string, now: number): RoomState {
  const idx = state.players.findIndex((p) => p.id === playerId);
  if (idx === -1 || state.players[idx].lastSeenAt === now) return state;
  const players = state.players.slice();
  players[idx] = { ...players[idx], lastSeenAt: now };
  return { ...state, players };
}

/** Opens round 1. Host only, lobby only. The caller supplies the already-fetched photo. */
export function start(
  state: RoomState,
  playerId: string,
  photo: PhotoMeta,
  now: number
): RoomResult {
  if (state.phase !== 'lobby') return { state, error: 'this game already started' };
  if (playerId !== state.hostId) return { state, error: 'only the host can start' };

  return { state: openRound(state, 1, photo, now) };
}

/**
 * Freezes the roster and opens a caption phase for `round`.
 *
 * The room's expiry is pushed out here as well: a 20-round game at the maximum
 * timers is exactly the 2h TTL, so a long game would otherwise be deleted from
 * under the players mid-round.
 */
function openRound(state: RoomState, round: number, photo: PhotoMeta, now: number): RoomState {
  return bump(
    state,
    {
      round,
      // The AI players are dropped from the roster from the round AFTER the one
      // that met the wall (rule 55). They stay in `players`, so they keep their
      // scoreboard row; they simply stop being someone the round waits for.
      roundPlayerIds: state.players
        .filter((p) => !(p.isBot && state.aiOffline === true))
        .map((p) => p.id),
      photo,
      captions: [],
      votes: {},
      botJobs: [],
      phaseEndsAt: now + state.options.captionSeconds * 1000,
      expiresAt: Math.max(state.expiresAt, now + ROOM_TTL_MS),
      photoRetry: undefined,
    },
    'caption',
    now
  );
}

// --- player actions ----------------------------------------------------------

/**
 * Records one caption. First write per player wins; the text is sanitized
 * (one line, trimmed, capped at CAPTION_MAX_CHARS by sanitizeCaption) and must
 * not be empty afterwards.
 * Ends the caption phase automatically once everyone in the round roster has
 * captioned.
 */
export function submitCaption(
  state: RoomState,
  playerId: string,
  text: string,
  captionId: string,
  now: number
): RoomResult {
  if (state.phase !== 'caption') return { state, error: 'not in the caption phase' };
  if (!state.players.some((p) => p.id === playerId)) return { state, error: 'player not in room' };
  if (!isInRound(state, playerId)) return { state, error: 'you are in from the next round' };
  if (state.captions.some((c) => c.playerId === playerId)) {
    return { state, error: 'you already captioned this round' };
  }

  // sanitizeCaption ENFORCES the cap (it trims at a word boundary), so the
  // length check that used to sit here could never fire: it was dead in every
  // round since the cap moved into text.ts, and it read as if an over-long
  // caption were rejected when it was actually being silently cut. Only the
  // empty case is a real error.
  const clean = sanitizeCaption(text);
  if (clean.length < 1) return { state, error: 'caption cannot be empty' };

  const caption: Caption = { id: captionId, playerId, text: clean };
  const withCaption: RoomState = {
    ...state,
    captions: [...state.captions, caption],
    version: state.version + 1,
  };

  if (allEligibleCaptioned(withCaption)) return endCaptionPhase(withCaption, now);
  return { state: withCaption };
}

/**
 * Ends the caption phase into vote, if it is actually over (everyone in the
 * roster captioned, or the timer passed). Otherwise a no-op, so it is safe to
 * call opportunistically from the alarm or from any request.
 */
export function endCaptionPhase(state: RoomState, now: number): RoomResult {
  if (state.phase !== 'caption') return { state };
  const timedOut = state.phaseEndsAt !== undefined && now >= state.phaseEndsAt;
  if (!allEligibleCaptioned(state) && !timedOut) return { state };

  const voting = bump(
    state,
    { votes: {}, phaseEndsAt: now + state.options.voteSeconds * 1000 },
    'vote',
    now
  );

  // A vote phase can be over the moment it opens: a round with fewer than two
  // captions is void whatever anyone does, so nobody should sit and watch a
  // 30-second timer run down on a ballot that cannot produce a winner.
  return endVotePhase(voting, now);
}

/**
 * Records one vote. First write per player wins; you cannot vote for your own
 * caption (also enforced in the view: your caption comes back canVote: false).
 * Ends the vote phase automatically once everyone who can vote has.
 */
export function submitVote(
  state: RoomState,
  playerId: string,
  captionId: string,
  now: number
): RoomResult {
  if (state.phase !== 'vote') return { state, error: 'not in the vote phase' };
  if (!state.players.some((p) => p.id === playerId)) return { state, error: 'player not in room' };
  if (!isInRound(state, playerId)) return { state, error: 'you are in from the next round' };
  if (playerId in state.votes) return { state, error: 'you already voted this round' };

  const caption = state.captions.find((c) => c.id === captionId);
  if (!caption) return { state, error: 'that caption is not in this round' };
  if (caption.playerId === playerId) return { state, error: 'you cannot vote for your own caption' };

  const withVote: RoomState = {
    ...state,
    votes: { ...state.votes, [playerId]: captionId },
    version: state.version + 1,
  };

  if (allEligibleVoted(withVote)) return endVotePhase(withVote, now);
  return { state: withVote };
}

/** Votes per caption id, plus which caption id(s) won. Every tied top caption wins. */
export function tally(
  captions: Caption[],
  votes: Record<string, string>
): { counts: Record<string, number>; winnerCaptionIds: string[] } {
  const counts: Record<string, number> = {};
  for (const c of captions) counts[c.id] = 0;
  for (const captionId of Object.values(votes)) {
    if (captionId in counts) counts[captionId] += 1;
  }
  const values = Object.values(counts);
  const max = values.length > 0 ? Math.max(...values) : 0;
  const winnerCaptionIds =
    max > 0
      ? Object.entries(counts)
          .filter(([, n]) => n === max)
          .map(([id]) => id)
      : [];
  return { counts, winnerCaptionIds };
}

/**
 * Why a void round scored nothing, in the terms a player can act on.
 *
 * A solo game with two AI players and a model that is down produces a round
 * where the only human wrote a caption and nothing else arrived. "Not enough
 * captions" reads as an accusation; "the AI players had nothing to say" is what
 * actually happened.
 *
 * Two conditions, not one (review round 4). A `failed` bot job is the tell, but
 * it only blames the AI when a HUMAN actually wrote something: a round where
 * everybody including the human went quiet is "nobody wrote anything", and
 * telling that player the AI let them down would be inventing a culprit.
 */
function voidReasonFor(state: RoomState): 'no-captions' | 'bots-failed' {
  const botIds = new Set(state.players.filter((p) => p.isBot).map((p) => p.id));
  const humanWrote = state.captions.some((c) => !botIds.has(c.playerId));
  if (!humanWrote) return 'no-captions';
  const botsFailed = state.botJobs.some(
    (j) => j.round === state.round && j.phase === 'caption' && j.status === 'failed'
  );
  return botsFailed ? 'bots-failed' : 'no-captions';
}

/**
 * Ends the vote phase into reveal, if it is actually over. Points = votes
 * received, awarded to every tied top caption's author. A round with fewer
 * than 2 captions is void: no winner, no points, represented as
 * `winnerCaptionIds: []` plus a `voidReason` on the RoundResult.
 */
export function endVotePhase(state: RoomState, now: number): RoomResult {
  if (state.phase !== 'vote') return { state };
  // Fewer than 2 captions is void no matter who votes, so the round is over the
  // moment it is in that shape: do not run a timer on an unwinnable ballot.
  const isVoid = state.captions.length < 2;
  const timedOut = state.phaseEndsAt !== undefined && now >= state.phaseEndsAt;
  if (!isVoid && !allEligibleVoted(state) && !timedOut) return { state };

  const { counts, winnerCaptionIds: tallied } = tally(state.captions, state.votes);
  const winnerCaptionIds = isVoid ? [] : tallied;

  const players = state.players.map((p) => {
    const won = winnerCaptionIds
      .map((id) => state.captions.find((c) => c.id === id))
      .filter((c): c is Caption => c !== undefined && c.playerId === p.id);
    if (won.length === 0) return p;
    const gained = won.reduce((sum, c) => sum + (counts[c.id] ?? 0), 0);
    return { ...p, score: p.score + gained };
  });

  const result: RoundResult = {
    round: state.round,
    photo: state.photo as PhotoMeta,
    captions: state.captions,
    votes: state.votes,
    winnerCaptionIds,
    ...(isVoid ? { voidReason: voidReasonFor(state) } : {}),
  };

  return {
    state: bump(
      { ...state, players },
      {
        history: [...state.history, result],
        phaseEndsAt: now + state.options.revealSeconds * 1000,
      },
      'reveal',
      now
    ),
  };
}

/**
 * Who won overall, or NOBODY.
 *
 * The zero guard is review round 7, must-fix 2. Without it every player is a
 * champion whenever every score is 0, and three live games in a row crowned two
 * bots that had never written a word as "joint champions" on 0 points. It is
 * also reachable in a perfectly healthy game: three friends caption every round
 * and nobody taps a vote, so every score stays 0. `done.ts` has had the right
 * branch for this since round 2 ("No champion this time.") and it was
 * unreachable, because the array was never empty while the room had players.
 */
function computeChampionIds(players: Player[]): string[] {
  if (players.length === 0) return [];
  const maxScore = Math.max(...players.map((p) => p.score));
  if (maxScore <= 0) return [];
  return players.filter((p) => p.score === maxScore).map((p) => p.id);
}

/**
 * Advances out of reveal: into the next round's caption phase (needs a photo,
 * see the header note) or into `done` after the last round.
 *
 * `actorId` is a player id (must be the host) or the literal 'timer' for the
 * reveal-timeout auto-advance. The host may only skip reveal once it has been
 * on screen for `revealMinMs` (the reveal floor); the timer only fires once
 * `phaseEndsAt` has passed. Calling it outside `reveal` is a silent no-op, so a
 * redundant host tap or a late alarm is harmless.
 */
export function advance(
  state: RoomState,
  actorId: string | 'timer',
  now: number,
  photo?: PhotoMeta,
  revealMinMs: number = REVEAL_MIN_MS
): AdvanceResult {
  if (state.phase !== 'reveal') return { state };

  if (actorId === 'timer') {
    if (state.phaseEndsAt !== undefined && now < state.phaseEndsAt) return { state };
  } else {
    if (actorId !== state.hostId) return { state, error: 'only the host can move on' };
    if (now < state.phaseStartedAt + revealMinMs) {
      return { state, error: 'give everyone a second to see the scores' };
    }
  }

  if (state.round >= state.options.rounds) {
    return {
      state: bump(
        state,
        { championIds: computeChampionIds(state.players), photoRetry: undefined },
        'done',
        now
      ),
    };
  }

  // ROUND 8 (must-fix 1(ii)): the ROLLOVER is the other place a game with no AI
  // players left has to end, and until now `noteAiOffline`'s shortcut was the
  // only thing that stopped one. That was fragile in both directions. Round 8
  // deliberately narrowed the shortcut so a round with captions in it finishes
  // (must-fix 1(i)), which means a solo room now reaches this line with
  // `aiOffline: true` and one human on the roster; and even before that change,
  // any path that set the flag without ending the room (the lobby branch, a
  // future caller) would have opened round after round with
  // `roundPlayerIds: ["host"]`, which is exactly the N-void-rounds bug rule 55
  // exists to kill.
  //
  // The guard is conditioned on `aiOffline`, NOT on the roster alone. A healthy
  // solo room (`botCount: 0`, one phone on the table) is a legal, if pointless,
  // game and must not be told the AI players are unavailable: nothing about it
  // involves the AI. Only a room whose bots were dropped BY THE WALL ends here.
  if (state.aiOffline === true) {
    const rosterAfterDrop = state.players.filter((p) => !p.isBot);
    if (rosterAfterDrop.length < 2) {
      return {
        state: bump(
          state,
          {
            championIds: computeChampionIds(state.players),
            endedReason: 'ai-unavailable',
            photoRetry: undefined,
          },
          'done',
          now
        ),
      };
    }
  }

  if (!photo) return { state, needsPhoto: true };
  return { state: openRound(state, state.round + 1, photo, now) };
}

/**
 * Runs every clock-driven transition that is due, in a loop, so a room that
 * nobody has polled for a while catches up in one pass. Stops as soon as it
 * needs a photo (the caller fetches one and calls again) or nothing more is
 * due. This is the pure core of the DO's `advanceIfDue`; the DO adds the photo
 * fetch and the storage write.
 */
export function advanceIfDue(
  state: RoomState,
  now: number,
  revealMinMs: number = REVEAL_MIN_MS
): AdvanceResult {
  let current = state;
  // At most one full round of transitions (caption -> vote -> reveal -> next)
  // can complete per call before a photo is needed, so 4 passes is the ceiling.
  for (let i = 0; i < 4; i++) {
    const before = current;

    if (current.phase === 'caption') current = endCaptionPhase(current, now).state;
    else if (current.phase === 'vote') current = endVotePhase(current, now).state;
    else if (current.phase === 'reveal') {
      const res = advance(current, 'timer', now, undefined, revealMinMs);
      if (res.needsPhoto) return { state: current, needsPhoto: true };
      current = res.state;
    }

    if (current === before) break;
  }
  return { state: current };
}

/**
 * Records that the next round's photo could not be fetched.
 *
 * Without this the room sits in `reveal` with `phaseEndsAt` already in the past,
 * the alarm re-arms to "now", and the Durable Object spins on outbound image
 * fetches until the room expires. So each failure gets a backoff, and after
 * PHOTO_MAX_ATTEMPTS the game ends honestly with `endedReason:
 * 'photo-unavailable'` and the scoreboard everyone already earned.
 *
 * IT BUMPS `version` (review round 5, must-fix). It used to be "bookkeeping
 * only", which was true until round 4 put `photoRetryAt` in the public view and
 * made both the lobby's Start and the reveal's Next read "Waiting for a
 * photo... 42s" off it. `handleState` answers `{ unchanged: true }` whenever the
 * client's `v` equals `room.version`, so without the bump a polling phone never
 * learned the countdown existed: the reveal screen said "Next round any moment."
 * for ever, and the host's Next button stayed enabled and did nothing. A state
 * change every player's screen renders is exactly what `version` is for.
 */
export function notePhotoFailure(
  state: RoomState,
  now: number,
  maxAttempts: number = PHOTO_MAX_ATTEMPTS
): RoomResult {
  const attempts = (state.photoRetry?.attempts ?? 0) + 1;

  if (attempts >= maxAttempts) {
    return {
      state: bump(
        state,
        {
          championIds: computeChampionIds(state.players),
          endedReason: 'photo-unavailable',
          photoRetry: undefined,
        },
        'done',
        now
      ),
    };
  }

  return {
    state: {
      ...state,
      photoRetry: { attempts, nextAttemptAt: now + photoRetryDelayMs(attempts) },
      version: state.version + 1,
    },
  };
}

/**
 * Workers AI has answered an ACCOUNT-level error, so no bot in this room will
 * write anything again today (review round 7, must-fix 1; plan rule 55).
 *
 * This is deliberately a DIFFERENT thing from a bot job failing. A failed job is
 * one model call hiccupping and the ladder retries it; this is the daily free
 * allocation being spent, which the retry ladder, the fallback vision model, the
 * judge and the guard are all powerless against, because there is no model on
 * the other end. Round 6's build treated the two as identical, so a solo game
 * voided every round in turn and then crowned the silent bots.
 *
 * What it does, once, and never again for this room:
 *   - sets `aiOffline`, which every screen renders as one plain sentence;
 *   - fails THIS round's still-open bot jobs with `failReason: 'ai-offline'`, so
 *     the round ends now rather than on the full caption timer;
 *   - and, if dropping the bots would leave fewer than two players in the next
 *     round's roster AND the round in progress cannot produce a result anyway,
 *     ends the game with `endedReason: 'ai-unavailable'` instead of walking a
 *     lone human through N unplayable rounds. A round with 2+ captions in it is
 *     finished first (round 8, must-fix 1; see the comment on that branch), and
 *     the game then ends at the rollover in `advance`.
 * The drop itself happens in `openRound`, which is what makes it "from the NEXT
 * round on": the current round keeps its roster so its jobs stay accounted for.
 *
 * Idempotent: a second call on an already-offline room changes nothing and does
 * not bump the version, because four bot jobs hit the same wall in the same
 * second and four version bumps would be four repaints of the same banner.
 */
export function noteAiOffline(state: RoomState, now: number): RoomResult {
  if (state.aiOffline === true) return { state };

  const botJobs = state.botJobs.map((job) =>
    job.round === state.round && job.status !== 'done'
      ? { ...job, status: 'failed' as const, failReason: 'ai-offline' as const }
      : job
  );

  // A lobby has not dealt anyone in yet and a finished game has nothing left to
  // end, so both only take the flag (and the banner that comes with it).
  //
  // The lobby branch is unreachable in production today (round 8, Claude nit 2):
  // bot jobs exist only in `caption` and `vote`, and `noteAiOffline` is called
  // only from `runDueBotJobs`. It is kept because it is the honest answer if a
  // later round ever pings a model from a lobby, and it is no longer the branch
  // that would resurrect the solo-void-rounds bug: the rollover guard in
  // `advance` now stops a flagged solo room whichever way it got flagged.
  if (state.phase === 'lobby' || state.phase === 'done') {
    return { state: { ...state, aiOffline: true, botJobs, version: state.version + 1 } };
  }

  // ROUND 8 (must-fix 1(i)): FINISH THE ROUND THE PLAYER ACTUALLY PLAYED.
  //
  // Round 7 ended a solo room from whatever phase it was in, which is right when
  // the wall arrives BEFORE a game and wrong when it arrives DURING one, and
  // during one is the normal way a daily allowance runs out (a round spends
  // several model calls, so the wall lands inside a round far more often than
  // between games). Jumping to `done` from a caption phase with two captions in
  // it, or from a live 3-caption ballot, deleted a round the player had played:
  // never scored, never revealed, `history: []`, `championIds: []`, and a
  // champion screen reading "0 points over 0 rounds".
  //
  // So the shortcut is now taken ONLY when the round in progress cannot produce
  // a result anyway:
  //   - `reveal`: the round is already scored and in `history`, there is nothing
  //     left to finish, so ending now is exactly rule 55's case;
  //   - the round can no longer REACH 2 captions (round 9 refines this from a
  //     raw count; see below), so `endVotePhase` voids it whatever anyone does,
  //     which is the shape round 7 actually observed live and the shape rule
  //     55's stated reason ("a lone human should not walk through the rest of
  //     the current round with nothing to vote on") describes.
  // With 2+ captions we take the flag only. `botGaveUp` already counts an
  // offline bot as having acted in EVERY phase, so `endCaptionPhase` /
  // `endVotePhase` close the round normally the moment the human acts or the
  // timer passes: scored, revealed, in the book. The game then ends at the
  // rollover, in `advance`, which is where the roster guard now lives.
  //
  // ROUND 9 (must-fix 1): the caption count is asked as a QUESTION ABOUT THE
  // FUTURE, not a snapshot. `state.captions.length < 2` is unreachable in the
  // vote phase (`endCaptionPhase` calls `endVotePhase` the instant it opens the
  // ballot, and `endVotePhase` voids on fewer than 2 captions and moves to
  // `reveal`), so the only phase it ever fired in was `caption` -- the one phase
  // where "fewer than 2 captions, which `endVotePhase` voids whatever anyone
  // does" is NOT true, because more captions can still arrive. One bot caption
  // in, wall on the second bot's call, human still typing: round 8 yanked the
  // caption screen away mid-sentence, refused their Send with "not in the
  // caption phase", threw the bot's caption away and printed the very
  // "nothing happened" champion screen rule 62 exists to kill.
  //
  // So the shortcut now counts the captions this round can still GET: the ones
  // already in plus every non-bot player in `roundPlayerIds` who has not
  // captioned yet. With 0 captions and nobody left to write one, the round is
  // genuinely dead and today's behaviour is kept exactly. With 1 caption and a
  // human still typing, we take the flag only: they finish the round they were
  // already sitting in; if the second caption never comes the round voids with
  // an honest `voidReason` and lands in the book, and the game ends at the
  // rollover instead of pretending the round never happened.
  const rosterAfterDrop = state.players.filter((p) => !p.isBot);
  const humansYetToCaption = state.roundPlayerIds.filter(
    (id) =>
      !state.players.find((p) => p.id === id)?.isBot &&
      !state.captions.some((c) => c.playerId === id)
  ).length;
  const roundCannotFinish =
    state.phase === 'reveal' || state.captions.length + humansYetToCaption < 2;
  if (rosterAfterDrop.length < 2 && roundCannotFinish) {
    return {
      state: bump(
        { ...state, aiOffline: true, botJobs },
        {
          championIds: computeChampionIds(state.players),
          endedReason: 'ai-unavailable',
          photoRetry: undefined,
        },
        'done',
        now
      ),
    };
  }

  return { state: { ...state, aiOffline: true, botJobs, version: state.version + 1 } };
}

/** True while a failed photo fetch is still serving out its backoff. */
export function photoRetryBlocked(state: RoomState, now: number): boolean {
  return state.photoRetry !== undefined && now < state.photoRetry.nextAttemptAt;
}

/**
 * Drops a spent photo backoff that nothing will ever consume (review round 5).
 *
 * Every other phase consumes a `photoRetry`: `advanceIfDue` returns
 * `needsPhoto` at a rollover, the fetch runs, and the attempt tally moves. The
 * LOBBY does not: `advanceIfDue` does nothing on a lobby state, so a failed
 * POST /start left a `photoRetry` behind that no code path would ever clear. It
 * spun the Durable Object's alarm (fixed in nextAlarmAt as well; two places,
 * because one is the symptom and this is the litter) and it kept `photoRetryAt`
 * in the public view, so the host's Start button would count down from a moment
 * that had already passed.
 *
 * CONSEQUENCE, in writing: in the lobby the attempt tally therefore resets once
 * a backoff expires, so a lobby can no longer reach `endedReason:
 * 'photo-unavailable'` on its own. That is deliberate. A room that never started
 * should not be marked over because an image host had a bad minute, and the
 * outbound rate is still bounded, by the backoff: at most one photo call per
 * PHOTO_RETRY_BACKOFF_MS, and only when a human taps Start. The hard attempt cap
 * still applies where it matters, on the AUTOMATIC mid-game rollovers, which are
 * the ones that would otherwise spin without anybody asking.
 */
export function clearSpentLobbyPhotoRetry(state: RoomState, now: number): RoomState {
  if (state.phase !== 'lobby') return state;
  if (state.photoRetry === undefined) return state;
  if (now < state.photoRetry.nextAttemptAt) return state;
  return { ...state, photoRetry: undefined };
}

// --- bot jobs ----------------------------------------------------------------
//
// Job bookkeeping deliberately does NOT bump `version`: jobs are internal, are
// stripped from every client view, and a status change must not invalidate the
// stamp a running job re-checks before it mutates the room.

export function enqueueBotJobs(state: RoomState, jobs: BotJob[]): RoomState {
  if (jobs.length === 0) return state;
  return { ...state, botJobs: [...state.botJobs, ...jobs] };
}

export function setJobStatus(
  state: RoomState,
  jobId: string,
  status: BotJob['status']
): RoomState {
  const idx = state.botJobs.findIndex((j) => j.jobId === jobId);
  if (idx === -1) return state;
  const botJobs = state.botJobs.slice();
  botJobs[idx] = { ...botJobs[idx], status };
  return { ...state, botJobs };
}

/** Takes the lease on a batch of jobs: status `running` plus the `startedAt` stamp. */
export function markJobsRunning(state: RoomState, jobIds: string[], now: number): RoomState {
  const wanted = new Set(jobIds);
  if (wanted.size === 0) return state;
  let changed = false;
  const botJobs = state.botJobs.map((job) => {
    if (!wanted.has(job.jobId)) return job;
    changed = true;
    return { ...job, status: 'running' as const, startedAt: now };
  });
  return changed ? { ...state, botJobs } : state;
}

/**
 * Marks every `pending` or `running` job past its `deadline` as `failed`.
 *
 * A `running` job whose Durable Object died mid-model-call would otherwise stay
 * `running` forever: never retried (only `pending` jobs are due) and never
 * recorded as finished. Called from the alarm and from settle, so the state
 * machine always converges on a terminal status.
 */
export function reapBotJobs(state: RoomState, now: number): RoomState {
  let changed = false;
  const botJobs = state.botJobs.map((job) => {
    const open = job.status === 'pending' || job.status === 'running';
    if (!open || now < job.deadline) return job;
    changed = true;
    return { ...job, status: 'failed' as const };
  });
  return changed ? { ...state, botJobs } : state;
}

/** A job is still worth running only while its own round and phase are the live ones. */
function isLive(state: RoomState, job: BotJob, now: number): boolean {
  return (
    job.status === 'pending' &&
    now < job.deadline &&
    job.round === state.round &&
    job.phase === state.phase
  );
}

/**
 * Jobs that should run now: live, due, and not a second attempt at work another
 * job already holds or finished. One (botId, round, phase) runs at most once
 * unless the earlier attempt is recorded `failed`.
 */
export function dueBotJobs(state: RoomState, now: number): BotJob[] {
  const claimed = new Set(
    state.botJobs
      .filter((j) => j.status === 'running' || j.status === 'done')
      .map((j) => `${j.botId}:${j.round}:${j.phase}`)
  );
  return state.botJobs.filter(
    (j) =>
      isLive(state, j, now) &&
      j.dueAt <= now &&
      !claimed.has(`${j.botId}:${j.round}:${j.phase}`)
  );
}

/**
 * The earliest moment a bot job wants the alarm to fire, if any: a PENDING job's
 * `dueAt` (run me) or a RUNNING job's `deadline` (reap me).
 *
 * The running half is review round 5, should-fix. `isLive` requires
 * `status === 'pending'`, so a job abandoned in `running` by a Durable Object
 * that died mid-model-call contributed no alarm at all, and the reap that ends
 * the round was delivered only by the next human poll. That was defensible while
 * the reap was a tidy-up; since round 5 it is load-bearing, because the reap is
 * what turns a bot that ran out of budget into "this bot has acted" and lets the
 * round move on. The server should not need a phone to notice its own deadline.
 */
export function nextBotJobDueAt(state: RoomState, now: number): number | undefined {
  const times: number[] = [];
  for (const job of state.botJobs) {
    if (job.round !== state.round || job.phase !== state.phase) continue;
    if (isLive(state, job, now)) times.push(job.dueAt);
    else if (job.status === 'running' && job.deadline > now) times.push(job.deadline);
  }
  return times.length > 0 ? Math.min(...times) : undefined;
}

// --- the client's view -------------------------------------------------------

/** The stable per-round display order, identical on every screen (seeded by code + round). */
export function orderedCaptions(state: RoomState): Caption[] {
  return seededShuffle(state.captions, hashSeed(`${state.code}:${state.round}`));
}

/**
 * The room as one specific player may see it (plan amendments 5 and 9):
 *   - bot jobs are stripped entirely
 *   - during `caption` a player sees only their own caption, so nobody can
 *     copy or pre-judge anyone else's
 *   - during `vote` every caption is a VoteCaption: id, text, isOwn, canVote,
 *     and NEVER an author
 *   - during `caption` and `vote` the live ballot is empty. `votes` is keyed by
 *     PLAYER ID, so shipping it before the reveal shows every screen who voted
 *     for which caption. Only the viewer's own vote comes back, as `yourVote`.
 *   - from `reveal` on, authors and the full ballot are attached
 *   - `serverTime` rides along so the client can measure its clock offset
 */
export function publicView(
  state: RoomState,
  viewerId: string,
  now: number,
  revealMinMs: number = REVEAL_MIN_MS
): PublicRoomState {
  const {
    botJobs: _botJobs,
    captions: _captions,
    votes: _votes,
    // Internal bookkeeping. The client is told the MOMENT (`photoRetryAt`
    // below) so a button can count down; the attempt tally is ours.
    photoRetry: _photoRetry,
    ...rest
  } = state;
  void _botJobs;
  void _captions;
  void _votes;
  void _photoRetry;

  const ballotIsSecret = state.phase === 'caption' || state.phase === 'vote';

  let captions: PublicCaption[];
  if (state.phase === 'lobby') {
    captions = [];
  } else if (state.phase === 'caption') {
    captions = state.captions
      .filter((c) => c.playerId === viewerId)
      .map((c) => ({ id: c.id, text: c.text, playerId: c.playerId }));
  } else if (state.phase === 'vote') {
    const voteCaptions: VoteCaption[] = orderedCaptions(state).map((c) => ({
      id: c.id,
      text: c.text,
      isOwn: c.playerId === viewerId,
      canVote: c.playerId !== viewerId,
    }));
    captions = voteCaptions;
  } else {
    captions = orderedCaptions(state).map((c) => ({
      id: c.id,
      text: c.text,
      playerId: c.playerId,
    }));
  }

  return {
    ...rest,
    captions,
    captionCount: state.captions.length,
    votes: ballotIsSecret ? {} : state.votes,
    yourVote: state.votes[viewerId] ?? null,
    revealMinMs,
    photoRetryAt: state.photoRetry?.nextAttemptAt ?? null,
    serverTime: now,
  };
}
